### ISSUE TITLE
Training Resolution in OWL-ViT

### ISSUE THREAD

**Issue by cuiziteng** [google-research/scenic#477]
Hello, thanks for the nice work~

I see the CLIP's resolution is a fixed parameter, because the position embedding shape is related to the image size (224, 224) or (384, 384). So what have you done to adapt the resolution in CLIP's visual encoder to 768x768, thanks!

**Comment by AlexeyG** [comment]
Hi @cuiziteng

Thank you for your interest in OWL-VIT. In order to be able to apply pre-trained CLIP models at a different resolution we resize their learned positional embeddings prior to fine-tuning them as part of OWL-ViT training. The actual code will be available as part of the open-source release of the trainable model. But as preview, the resizing looks very similar to the code for the Scenic ViT baseline: https://github.com/google-research/scenic/blob/main/scenic/projects/baselines/vit.py#L428
