### ISSUE TITLE
best threshold score for the Evaluation

### ISSUE THREAD

**Issue by nimakasipour** [google-research/scenic#657]
I am evaluating your model using the Coco dataset val2017 for my master thesis with text and image queries.
The question is, what is the best threshold for your model?
I am using the following model and processor:

model = OwlViTForObjectDetection.from_pretrained("google/owlvit-base-patch32")
processor = OwlViTProcessor.from_pretrained("google/owlvit-base-patch32")

> for Zero-Shot Object Detection with OWL-ViT using textprompt:

The **threshold score = 0.1** works fine.
I have reproduced the evaluation results on your paper in the coco dataset. 

BUT the problem is in practice if you ONLY enter one text query like "cat" and try to find it in an image 
the model finds too many objects as "cat" and the FP is very high.

> for Image-Guided Object Detection with OWL-ViT:

isually I find out
**score_threshold=0.6 nms_threshold=0.3**
works well for many images, but not always.

this is where I have doubts about using your model for my thesis. i could not find any information regarding threshold and evaluating Image-Guided Object Detection in your paper. could you please help me with this?

**Comment by mjlm** [comment]
For the official COCO evaluation (see [here](https://github.com/cocodataset/cocoapi)), setting a threshold is not necessary because the metric chooses which predictions to consider in a different way, without an explicit threshold.

If you need the threshold for some other evaluation, or for display, you will have to find a good threshold by trial and error.

One way to do this is to take part of your dataset and try many different thresholds on that dataset to see which one gives the best result/metric. You can then use that threshold on the remaining data to get the final test metric.
