### ISSUE TITLE
OWL_VIT model's RAM required 

### ISSUE THREAD

**Issue by kent252** [google-research/scenic#660]
I am a new researcher and I am evaluating your model using the LVIS dataset val2017 for my research. I ran the following command in colab with 85gb RAM:
  python -m scenic.projects.owl_vit.evaluator \
    --alsologtostderr=true \
    --platform=gpu \
    --config=scenic/projects/owl_vit/configs/clip_b32.py \
    --checkpoint_path=gs://scenic-bucket/owl_vit/checkpoints/clip_vit_b32_b0203fc \
    --annotations_path=${HOME}/annotations/lvis_v1_val.json \
    --tfds_data_dir=//your/data/dir \
    --output_dir=/tmp/evaluator 
BUT the process always out of memory and killed itself. The question is, what is the minimum requirements for RAM to run evaluate OWL-VIT. Could you please help me with this?

**Comment by AlexeyG** [comment]
Hi @kent252 

RAM usage grows linearly with dataset size. You can run evaluation on a part of the validation set and extrapolate that to see what the RAM usage would be for the entire validation set.

**Comment by mjlm** [comment]
While the evaluator does require large amounts of RAM, 85GB seem like a lot. The images are not stored during evaluation, only the predictions. I'm wondering if this is an issue with garbage collection. You could try adding

```py
import gc
gc.collect()
```

to the main predict loop (perhaps so that it executes on every 10th batch).

I'll close this issue now since it's quite old, please feel free to reopen if it persists.
