### ISSUE TITLE
Request to improve small object detection accuracy in OWL-VIT model

### ISSUE THREAD

**Issue by Aasthaengg** [google-research/scenic#731]
Hello, 
I have been utilizing **OWL-VIT** model for object detection and have observed an exceptional performance in detecting larger objects. However, the model's current limitations in detecting smaller objects can hinder its efficacy in several applications.
I have attached a sample from HuggingFace Demo. 

I have raised this issue to request a discussion on how the model's accuracy can be improved in detecting smaller objects. I have researched the model's architecture and training strategies and have some ideas that I believe could help achieve this goal. I believe that enhancing its accuracy in small object detection can be accomplished by implementing methods like Slicing Aided Hyper Inference.

I am interested to contribute to help elevate the model's performance in detecting smaller objects and would be delighted to receive your feedback on it. 

Thank you. 

<img src="https://user-images.githubusercontent.com/82709402/227361647-329dfb5b-c6ae-473f-8098-c86fe170288c.png" alt="Screenshot from 2023-03-23 13-46-49" width="700" height="400">

<img src="https://user-images.githubusercontent.com/82709402/227659395-25801e1d-1f93-4147-b232-e89b3ef11993.png" alt="Screenshot from 2023-03-24 14-46-04" width="500" height="400">

**Comment by mjlm** [comment]
Hi @Aasthaengg,

Thanks for raising this issue. I have a few tips for improving small-object detection without major changes to the architecture:

* Use the largest possible resolution and smallest patch size. If you've been using the B/32 model, try B/16 or L14 models.
* Use OWLv2. Since you posted this issue, we have published OWLv2 model checkpoints (see [README](https://github.com/google-research/scenic/tree/main/scenic/projects/owl_vit)). These models use larger resolution (1008 x 1008 for the L/14 models) and were trained with more aggressive mosaics and size augmentation than OWLv2. They are significantly better at small-object detection, e.g. the `OWLv2 CLIP L/14 ST+FT` model reaches 32.6 LVIS APs, compared with 22.2 for the OWLv1 L/14 model.

Please try the new models and let us know how it goes!

**Comment by mjlm** [comment]
I'll close this for now, please re-open if you're still working on this.
